### ISSUE TITLE
Add automatic builds using GitHub actions and the official "builder" 

### ISSUE THREAD

**Issue by Jalle19** [Jalle19/home-assistant-addon-repository#1]
https://developers.home-assistant.io/docs/add-ons/publishing

**Comment by tomrosenback** [comment]
"image" parameter in Dockerfile removed as we don´t have a prebuilt image, yet.

**Comment by Jalle19** [comment]
It seemed to be needed for the builder to actually work

**Comment by Jalle19** [comment]
@tomrosenback if I want to try this right now, what should I do? Will the addon by built locally on my Home Assistant machine now that `image` is commented out?

**Comment by Jalle19** [comment]
And can I still copy the addon directory to `addons` on Home Assistant OS and use it as a local add-on? That's how I've done things so far (good old "copy files to deploy" strategy).

**Comment by tomrosenback** [comment]
To test this, go to Addons store, click the 3 dots in the upper right corner, repositories, there add https://github.com/Jalle19/home-assistant-addon-repository and the addon(s) from this repo will appear on the screen under "Jalle19 Home Assistant add-on repository". From just click install and configure.

Yes you can have both the local addon (which I suppose you have in the addons/local folder) and the one from this repo installed at the same time. You need however to stop all but the one you are about to test as the USB port otherwise will be busy.

**Comment by tomrosenback** [comment]
> It seemed to be needed for the builder to actually work

Was not able to install the addon when the image was set, so I guess it requires some iteration still to make that work correctly. 

> @tomrosenback if I want to try this right now, what should I do? Will the addon by built locally on my Home Assistant machine now that `image` is commented out?

Yes it will be built locally.

**Comment by tomrosenback** [comment]
I tried to enable the image property back, but GitHub actions doesn´t seem to manage to upload the images to docker. @Jalle19 could you check this as this is your repo? I played around a bit with the naming of the image and the slug, but I don´t know what would be the "best"...

**Comment by tomrosenback** [comment]
@Jalle19 sorted the push to docker hub now, remains the naming convention then. What do you say? 
eg now hassos-amd64-eda-modbus-bridge would be homeassistant-eda-modbus-bridge-amd64 and likewise for the slug hassos_eda_modbus_bridge should be homeassistant_eda_modbus_bridge or jalle19_eda_modbus_bridge

What do you think?

**Comment by Jalle19** [comment]
I don't really have any opinion on this, no one uses these repositories directly anyway, it's all done automatically by Supervisor, right?

**Comment by tomrosenback** [comment]
You are probably right, noticed that they had similar naming convention in the docs linked above so I guess this is good as is.

**Comment by tomrosenback** [comment]
Maybe we can close this then?

**Comment by Jalle19** [comment]
Sure, let's close it. Thanks for the work so far, I'll try this out myself soon!

**Comment by Jalle19** [comment]
Installed via the repository now - it seemed grab the pre-built image from the registry, so I guess it all works. I'll get to work on the READMEs.

**Comment by tomrosenback** [comment]
Yes I made it work, previously the config.json had version "latest" which is not a versionnumber, but when changing that to 1.0.0 it broke due to the --test flag.
