### ISSUE TITLE
Change default update interval

### ISSUE THREAD

**Issue by tomrosenback** [Jalle19/home-assistant-addon-repository#14]
As written in some earlier issue, for me having the 10s update interval locked the ModBus interface on the unit itself from time to time. After changing the configuration in HA to 60s it has worked flawlessly. 

Should we change the default to 60 instead of 10? Affected file config.json

**Comment by Jalle19** [comment]
60 second intervals seem a bit sparse :/ Have you tried anything in between, like 20 seconds?

**Comment by Jalle19** [comment]
Feel free to make a PR for 60 seconds, we could add a note to DOCS.md that the value is conservative to work with as many units as possible and that a lower value like 10 seconds could work fine too?

**Comment by tomrosenback** [comment]
I have not tried with anything else than 10 and 60, 10 gave me problems, 60 not. As this only affects readings and alarms I am at least fine with 60s as interval, temperatures and humidity doesn´t change that fast, modes and settings are published back ASAP anyway.

I will create a PR with the change and note in DOCS.md, after that I am fine with releasing.
