### ISSUE TITLE
Automatic reconnect to MQTT not working during startup

### ISSUE THREAD

**Issue by tomrosenback** [Jalle19/home-assistant-addon-repository#22]
In some cases the MQTT service has not started before this addon is starting, this causes the addon to fail to connect and then it remains disconnected forever and never reconnects.

![image](https://user-images.githubusercontent.com/18549343/229487447-b59ff98b-7e36-4ecc-915c-fbdb4dcbb744.png)

**Comment by Jalle19** [comment]
Perhaps this is related to https://github.com/Jalle19/home-assistant-addon-repository/issues/17

**Comment by tomrosenback** [comment]
> Perhaps this is related to #17

I think in #17 we can assume the MQTT service running already.

**Comment by Jalle19** [comment]
Moving this issue to https://github.com/Jalle19/eda-modbus-bridge/issues/61
