### ISSUE TITLE
Simplify MQTT configuration

### ISSUE THREAD

**Issue by tomrosenback** [Jalle19/home-assistant-addon-repository#9]
Use bashio::service to get MQTT connection details and hence remove configuration needs for MQTT as this is a required service for this addon.

**Comment by Jalle19** [comment]
Sounds good, can you implement it? I'm very unfamiliar with bashio in general, I barely managed to get the initial version working :D

**Comment by tomrosenback** [comment]
Absolutely, I was about to do it already in the bump version PR #6 but thought it is better to have it separately.
